FROM node:16-buster-slim

ARG PG_HOST_ARG 
ARG PG_USER_ARG
ARG PG_PASSWORD_ARG
ARG PG_PORT_ARG
ARG PG_DB_ARG
ARG JWT_SIGN_KEY_ARG

ENV HOST 0.0.0.0
ENV PORT 4321
ENV PG_HOST $PG_HOST_ARG
ENV PG_USER $PG_USER_ARG
ENV PG_PASSWORD $PG_PASSWORD_ARG
ENV PG_PORT $PG_PORT_ARG
ENV PG_DB $PG_DB_ARG
ENV JWT_SIGN_KEY $JWT_SIGN_KEY_ARG

WORKDIR /usr/src/app
COPY package*.json ./

RUN npm install
COPY *.js ./
COPY src ./src/
EXPOSE 4321
CMD [ "node", "app.js" ]
