name: Close stale pull requests actions

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  close-stale-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Close stale pull requests
        uses: peter-evans/close-pull@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-days: 1
