name: Close PR after 7 days

on:
  schedule:
    - cron: '0 0 * * *' # Run every day at midnight

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Close PR after 7 days
        run: |
          sudo apt install jq -y
          
          token="${{ secrets.GITHUB_TOKEN }}"
          repo="${{ github.repository }}"
          curl -H "Authorization: token $token" \
               -H "Accept: application/vnd.github.v3+json" \
               -X GET "https://api.github.com/repos/$repo/pulls?state=open&sort=created&direction=asc" \
               | jq '.[] | select((now - .created_at | fromdateiso8601) > 604800) | .number' \
               | xargs -I{} curl -H "Authorization: token $token" \
                                    -H "Accept: application/vnd.github.v3+json" \
                                    -X PATCH "https://api.github.com/repos/$repo/pulls/{}/" \
                                    -d '{"state": "closed"}'
