name: Close Pull Requests after 7 days

on:
  schedule:
    - cron: '0 0 * * *' # Run at midnight every day

  workflow_dispatch:

jobs:
  close_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: printenv

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Close old pull requests
        run: |
          pull_requests=$(curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" -s "https://api.github.com/repos/${{ github.repository }}/pulls")
          for pr in $(echo "${pull_requests}" | jq -r '.[] | select((now - (.updated_at | fromdateiso8601)) > 60) | .number'); do
            echo $pr
            curl -s -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/$pr" -d '{"state": "closed"}'
          done
