name: Close stale pull requests
on:
  schedule:
    # Run the workflow every day at 12:00 UTC
    - cron: '0 12 * * *'
    
  workflow_dispatch:
  
jobs:
  close-stale-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Close stale pull requests
        run: |
          token=${{ secrets.GITHUB_TOKEN }}
          days=7
          stale_date=$(date -u -d "${days} days ago" +"%Y-%m-%dT%H:%M:%SZ")
          query="is:open is:pr created:<${stale_date}"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $token" \
            https://api.github.com/repos/${{ github.repository }}/issues \
            -d "{\"state\": \"closed\", \"labels\": [], \"assignees\": [], \"milestone\": null, \"updated_at\": \"${stale_date}\", \"q\": \"${query}\"}"
